# ===============================
# 📘 config.yaml — SPN Training Config
# ===============================

project: "mnist_spn"
mode: "learn_spn"   # options: learn_spn | quad_spn

dataset:
  name: "MNIST"
  root: "datasets"
  n_train: 50000
  n_val: 10000
  batch_size: 64

training:
  lr: 0.01
  epochs: 10
  weight_decay: 0.000001
  device: "cuda"
  save_path: "best_circuit.pth"

learn_spn:
  alpha: 0.5
  min_instances: 1000
  mi_quantile: 0.6
  jitter_scale: 0.5
  use_miwae: false
  num_input_units: 1
  num_sum_units: 1
  image_shape: [1, 28, 28]

quad_spn:
  alpha: 5.0
  jitter_scale: 0.5
  use_miwae: false
  num_input_units: 1
  num_sum_units: 1
  image_shape: [1, 28, 28]

logging:
  use_wandb: true
