project: "mnist_spn"

dataset:
  name: "MNIST"
  root: "datasets"
  valid_split_percentage: 0.05
  batch_size: 256

training:
  lr: 0.01
  epochs: 200
  weight_decay: 0.0
  T_0: 1
  eta_min: 0.0001
  validation_steps: 250
  delta: 0.0
  patience: 5
  device: "cuda"
  save_path: "best_circuit.pth"

learn_spn:
  alpha: 5.0
  noise_scale: 2.0
  use_miwae: false
  sum_product_layer: "cp"
  activation: "softmax"
  weights_init: "normal"
  region_graph: "quad-graph"
  num_input_units: 1
  num_sum_units: 1
  use_estimated_weights: false
  use_mixing_weights: true
  image_shape: [1, 28, 28]

logging:
  use_wandb: false
