project: "mnist_spn"

dataset:
  name: "MNIST"
  root: "datasets"
  n_train: 50000
  n_val: 10000
  batch_size: 64

training:
  lr: 0.01
  epochs: 10
  weight_decay: 0.000001
  device: "cuda"
  save_path: "best_circuit.pth"

learn_spn:
  alpha: 5.0
  noise_scale: 2.0
  use_miwae: false
  sum_product_layer: "cp"
  activation: "softmax"
  weights_init: "normal"
  region_graph: "quad-graph"
  num_input_units: 1
  num_sum_units: 1
  use_estimated_weights: true
  use_mixing_weights: false
  image_shape: [1, 28, 28]

logging:
  use_wandb: false
